### ISSUE TITLE
[Epic] ESI Information Gathering

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#1]
Gathering the motivation and the requirements for ESI.
Having the motivation part of the discussion be driven by the PIs.
Gather an understanding of what part MOC should have in ESI's next steps.
Translate into a set of epics/requirements that we can start investigating.

[Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvODAwNTU)

**Comment by msdisme** [comment]
https://drive.google.com/drive/folders/1VUDTjGzoUj4svvKgcRRTwdSzuXQMTEHg has a great deal of this information captured already and we shoudl start there.

**Comment by msdisme** [comment]
this is not a complete list; but a starting point.

[ESI Folder](https://drive.google.com/drive/folders/1VUDTjGzoUj4svvKgcRRTwdSzuXQMTEHg)

[ESI install on CloudLab boss node](https://docs.google.com/document/d/1-wqev7KQ6q_KCY8GPE9BXe15N3xr0fEcISqMwsI4v8w/edit?usp=sharing)

The [Current State of ESI presentation](https://docs.google.com/presentation/d/1W2qqAoFT4BOQ3R8oSEdvVEupaZ4sana2IspOlQO_Qkw/edit#slide=id.gf76ca16445_1_0) , to set context.

The Pilot Deployment Test Cases - [ESI System Testing](https://docs.google.com/document/d/1IuqLqN-vxgstG8Nb0gPdxSiIn3tu_yfN1IhhP5KxA_E/edit)

[ESI Operate First Use Cases 2021](https://docs.google.com/document/d/12G4w9Os2bIUbL8ZadxCYVUSU0ZOo12_YW-6dAaWM0DA/edit)

**Comment by hpdempsey** [comment]
On Tue, Sep 13, 2022 at 3:03 PM Heidi Dempsey ***@***.***> wrote:

> Kim,
>
> We have been working on this for a while already (i.e. years).  Let's talk
> about it when I get back from Brno next week.  I'm not quite sure what you
> have in mind from this brief note, but I'm sure we should coordinate on it.
> Heidi
>

Do you want to set up a time to talk Thurs or Friday?

**Comment by hpdempsey** [comment]
Kim,

We have been working on this for a while already (i.e. years).  Let's talk
about it when I get back from Brno next week.  I'm not quite sure what you
have in mind from this brief note, but I'm sure we should coordinate on it.
Heidi

**Comment by joachimweyl** [comment]
Initial meeting planned and attended. Meeting came to the conclusion that we will require more input from Orran.
