### ISSUE TITLE
[Epic] Integration of NERC OCP Prod with ColdFront and Keycloak

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/epics#2]
# Motivation
For the NERC OpenStack deployment we’re currently handling authentications with Single Sign-On with OpenID Connect using Keycloak. For resource allocation (project creations) we’re using ColdFront. We want to keep using these same systems for the NERC OCP Prod. [1][2]

# Completion criteria
Satisfies the acceptance criteria defined at [3]. In summary, users can authenticate using their institutional log in. Users can create projects on OpenShift and manage the users that have access to that project. Users can request and change quotas associated with the project. Administrators of the cloud can approve or deny new projects and change quota requests.

# Description
OpenShift already supports using OpenID Connect for authentication and we’re already using that in our MOC clusters. So there’s already prior work we can base this integration on. [4] Of note is that users shouldn’t be able to create projects, but only be able to see projects they have been added to, because project creation and access management is handled by ColdFront on their behalf.

For integrating with ColdFront, support has already merged on the coldfront plugin that we’re using for managing OpenStack. [5]

This plugin does not directly integrate with OpenShift however.

Early on in the design process we made the case that we needed to define a standard API, so that we wouldn’t have to write a driver for each of the services that wants to integrate into our resource allocation management systems. Work on defining that standard is still ongoing [6], however that initial draft implementation is the cci-moc/openshift-acct-mgt project. [7]

The above service is what the plugin does integrate with.

Integration between ColdFront, Keycloak and openshift-acct-mgt and OCP has already been tested in MOC OCP-Staging where there is a live deployment of ColdFront and openshift-acct-mgt.

The integration of the above with OCP Prod is based on the work to deploy the above in MOC OCP-Staging.

# References

1. [NERC Authentication - Technical Details](https://docs.google.com/document/d/1MbyamEptPJGX7WM9wxcSThAEduVeFdiD3CfrYPADOZs/edit)
2. [NERC AuthZ and Stored Information](https://docs.google.com/document/d/1qoPOPE9OJZSf9GKjJa8yQyCJfNNlAmJJVohjbkBKZlc/edit)
3. [NERC/OpenShift Acceptance Tests](https://docs.google.com/document/d/18AUzxuFWKeNOO6UFgze6Tm1mF1Gz-UIMj8Wqu6lyxcc/edit)
4. [Enable moc-sso #24](https://github.com/CCI-MOC/moc-apps/pull/24)
5. [coldfront-plugin-cloud](https://github.com/nerc-project/coldfront-plugin-cloud)
6. [Investigate a possible implementation of the SCIM API #68](https://github.com/CCI-MOC/openshift-acct-mgt/issues/68)
7. [openshift-acct-mgt](https://github.com/CCI-MOC/openshift-acct-mgt)

# Changelog
2022-09-20: Initial description
2022-09-20: made references text with links
2022-11-07: add an epic link

[Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvODA3NDU)

**Comment by joachimweyl** [comment]
@knikolla I really like the use of the Changelog on the description since that can change without being tracked. I have 3 questions for you. Normally these would have come up as discussions in this Epic. Since this Epic is being created after the majority of the work was done I think it could be helpful to capture some of this information in the comments.
1. What lessons did we learn along the way?
1. Did we bump into any unexpected roadblocks?
1. Have there been any bug fixes that we learned something valuable?

**Comment by joachimweyl** [comment]
Epic closed as coldfront & keycloak are being used by NERC OpenShift.
