### ISSUE TITLE
[Epic] Gateway Storage - iscsi on top of RBD

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#38]
# Motivation
Determine if we can use iSCSI on top of RBD

# Completion criteria
Prove iSCSI can be used on RBD or not

# Description
1. Gather a team to test
1. Determine if it is viable
1. If it is build and test

# References
1. [Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTExNDA4)

# Changelog
2022-12-15: Added Epic link

**Comment by naved001** [comment]
Where's this coming from? We already use iSCSI on top of RBD, and as far as I know we want to stop using iSCSI for something better in the future.

**Comment by joachimweyl** [comment]
[Priorities list](https://docs.google.com/document/d/1oIiZYQdZ9JBWHzYUuXLW5WUAHg7Olcd4_wjZZTmPVm8/edit?usp=sharing), if this is done great. And yes we do want to stop using iSCSI but first, we wanted to make sure it worked and gather what data we can from it for future steps.
