### ISSUE TITLE
[Epic] Johonnot HW deliveries

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/epics#4]
Oct 6 initial 22 pallets
2-3 weeks later 22 more
details on network gear to follow

# Motivation
*Why are we doing this?*

# Completion criteria
*Definition of Done*

# Description

# References
1. [document](https://docs.google.com)

# Changelog
2022-11-07: add epic link

[Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvODI3MzY)

**Comment by joachimweyl** [comment]
linked epic closed
