### ISSUE TITLE
[Epic] XDMoD NERC OpenStack Data Integration for Reporting

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#7]
# Motivation
We need to shred the OpenStack data and present it to meet the NERC requirements.

# Completion criteria
XDMoD provides OpenStack data to the XDMoD dashboard. Able to track required information for all OpenStack instances.

# Description
XDMod provided a specific OpenStack raw data structure. We need to ensure we are pulling for this specific data.

# References
1. [Open XDMoD](https://open.xdmod.org/10.0/index.html)

# Changelog
2022-11-09: updated projects to instances in completion criteria

[Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvNzM3MDE)

**Comment by joachimweyl** [comment]
1. Based on Greg's explanation Rob infers that the files need to be processed in order
   1. We know from the log file that they were not processed in order.
1. He also states "volumes are tracked by VM"
   1. this is problematic because we create a volume without a VM so that we can boot from volume (ie, have a larger or smaller boot volume based on what we are deploying on that VM)
   2. people will sometime keep volumes around after the VM associated with them is deleted - this disk usage probably will not be tracked correctly
1. @rob-baron will be working on
   1. running SQL statements Greg suggested
   1. "pull out a potential counter-example in the test data from his (Greg's) assertion and have him explain it"

**Comment by rob-baron** [comment]
@joachimweyl 

Assuming that what greg states, they seem to have very specific use cases which will need to be expanded to our use cases. 

It is my memory that here is a counter-example in the test data.  However, I have the suspicion that the majority of case, a vm is created, the disk is created, then the disk is attached, then the disks unattached and deleted, then the vm is deleted.

**Comment by joachimweyl** [comment]
@rob-baron please see the rewording in my [original comment](https://github.com/CCI-MOC/epics/issues/7#issuecomment-1290807570), I misunderstood your slack message.

**Comment by rob-baron** [comment]
@joachimweyl I added to your comment comment as opposed to repeating it in my comment (to give enough context).

**Comment by joachimweyl** [comment]
XDMoD let us know that they are aggregating the data based on the instance. This is an issue because volumes not associated with an instance are ignored.

**Comment by joachimweyl** [comment]
linked epic closed.
