### ISSUE TITLE
[Epic] Direct Billing for researchers at non-MOU institutions

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/epics#75]
# Direct Billing for Researchers at Non-MOU Institutions

## Motivation

Currently, universities with Memorandums of Understanding (MOU) have the convenience of receiving bills for individual researchers and projects. However, many institutions that do not have an MOU in place still host numerous researchers who use our services. To ensure fairness, accessibility, and broadened utilization of our services, we need a method to directly bill individual researchers at universities without MOUs.

## Completion Criteria
**Definition of Done**
1. A billing mechanism is developed and tested to accurately bill individual researchers at non-MOU institutions.
2. User interface for individual researchers at non-MOU institutions to set up and manage their billing details is user-friendly and secure.
3. Researchers can easily track their expenses and view detailed invoices.
4. Institutions without MOU are informed and educated on the new billing process.
5. Support mechanisms (e.g., FAQ, helpdesk) are set up to handle any queries related to the billing process for non-MOU researchers.
6. The system seamlessly integrates with the existing billing and financial systems.
7. Adequate documentation is prepared for both technical maintenance and user guidance.
8. Internal staff are trained on the new billing process, and potential issues and resolutions.

## Description

This epic focuses on developing a robust billing method tailored to individual researchers at non-MOU institutions. Unlike the existing system where MOU institutions receive a collective bill, the proposed method will allow each researcher from non-MOU institutions to be billed directly, giving them full transparency and control over their project expenses. The initiative will involve designing a secure and user-friendly interface, back-end integrations, and an awareness campaign targeting potential users. Moreover, support systems will be set up to ensure that users have a smooth experience and can address any issues or queries promptly.

## References
1. [ZenHub Epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTU4NDEz)

## Changelog
* Oct 2, 2023: Initial creation of the epic based on the need identified for direct billing of researchers at non-MOU institutions.
* [Date, update/progress made]
* [Date, any further changes or updates]
* 2023-11-06 - added link to Zenhub Epic

**Comment by knikolla** [comment]
@msdisme the "document" link in references only links to docs.google.com and not a specific document.

**Comment by msdisme** [comment]
yep- left it in as part of template but see how it could be confusing
