### ISSUE TITLE
[Epic]Hardware Utilization Dashboard

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#78]
# Motivation
As a person with administrative responsibilities for the NERC I want the ability to see the patterns of behavior in the usage patterns.   

Due to the elasticity of the hardware in use this should not be based upon utilization, though utilization should also be visible or easily available since that information will inform decisions about hardware requirements. 

We want to be able to see the growth of the number of users, virtual cpu's, OpenShift containers and storage.   Grafana is a tool that is able to do this and therefore we will start by seeing what we can create with Grafana.

# Completion criteria
Grafana dashboard created
Display cluster hardware information
- CPU growth and utilization vs current cpu
- RAM growth and utilization vs current cpu
- GPU growth and utilization vs current cpu
- Storage growth and utilization vs current cpu

# Description
Create a Grafana Dashboard that can display hardware utilization for OpenStack and OpenShift Utlization.

# References
1. [ZenHub Epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTYzNzQw)

# Changelog
2023-10-27: Updated ZenHub Link
2023-11-30: Rewrote to include Administrative Role, Removed Grafana from title since we are open to other options, Added storage utilization and the idea that utilization should be part of this, though not primary. Clarified OpenStack and Openshift inclusion

**Comment by msdisme** [comment]
Include Billed vs not billed.

**Comment by msdisme** [comment]
Start with monthly report in Curator
What currently exists and where?
Where tracked, may it be automated?
-start with a new epic to gather data into a single 

Wishlist: 
Number of users
Number of projects
Number of institutions
Different Services - openshift vs openstack vs. opeshift AI
For Openshift - diffferent clusters
- size and % utilization
