### ISSUE TITLE
[Epic] non-gdpr EULA

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/epics#8]
# Motivation
- We need a EULA in place for users of the NERC to ensure PI's and users understand the "rulesof the road"
- current version needs to exclude GDPR and similar privacy regimes until that is addressed by OGC and agreement 

# Completion criteria
- initial use case NERC OpenShift
- agreed to by OGC at BU and HU

- entire completion would include OpenStack and other MOCA affiliated projects using this. 

# Description
- Standard EULA, based on

# References

# Changelog
2022-11-07: added a placeholder for Epic

[Epic](temp.com)

**Comment by joachimweyl** [comment]
linked epic closed.
